### ISSUE TITLE
optionalBuffer is broken

### ISSUE THREAD

**Issue by pfmooney** [mcavage/node-assert-plus#20]
```
> var assert = require('assert-plus');
undefined
> var buf = new Buffer(1);
undefined
> assert.buffer(buf);
undefined
> assert.optionalBuffer(buf);
AssertionError: buffer (buffer) is required
    at repl:1:8
    at REPLServer.self.eval (repl.js:110:21)
    at repl.js:249:20
    at REPLServer.self.eval (repl.js:122:7)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.emit (events.js:95:17)
    at Interface._onLine (readline.js:203:10)
    at Interface._line (readline.js:532:8)
    at Interface._ttyWrite (readline.js:761:14)
    at ReadStream.onkeypress (readline.js:100:10)
```

**Comment by pfmooney** [comment]
Fixed in v0.2.0
